### ISSUE TITLE
Tekton Latest Pipeline Run does not always show the data.

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-plugins#735] opened 2023-09-14 15:08 UTC
**Describe the bug**
Bug on behalf of Natale.

The data is not always visible in the LPR plugin in the CI tab. Sometimes it will display 'No Pipeline Run to visualize'

**To Reproduce**

1. Go to 'Catalog' Page
2. Click on a component that has Tekton enabled.
3. Click ok the 'CI' tab
4. Most of the time the data will be displayed, and sometimes not as seen in the screenshot below.

**Expected behavior**
The data should be visible every time.

**Screenshots**

![lpr1](https://github.com/janus-idp/backstage-plugins/assets/6601523/a200fd95-e405-4dfb-90e0-efd290e5c097)

![lpr2](https://github.com/janus-idp/backstage-plugins/assets/6601523/3b8fc12a-446f-4b37-8fa2-3a39e962aceb)

**Additional context**

**Comment by jerolimov** [comment] 2023-11-16 18:46
I tried to reproduce this issue multiple times with the Pipeline Run list page.

I close this issue because the "Latest Pipeline Run" component isn't shown anymore above the Pipeline Run list, so this might be fixed that redesign.

**Comment by debsmita1** [comment] 2023-11-22 18:39
Reopening this issue as I am able to reproduce it

https://github.com/janus-idp/backstage-plugins/assets/22490998/e25ad2bf-4741-4de3-a704-34f1daf4ce0d

**Comment by gashcrumb** [comment] 2023-12-01 13:01
I haven't reproduced this yet locally, but if it's due to flaky DNS we may not have much option other than maybe doing x number of retries before giving up and reporting the failure.  

Is this FETCH_ERROR type used for any kind of problem fetching data from the API server?  It may be difficult then to discern what could be a temporary failure which would be suitable for retries vs immediately reported to the user.

**Comment by gashcrumb** [comment] 2023-12-04 13:04
So far the closest I've gotten to reproducing this is a 504 gateway timeout being reported, I was booting up the cluster and happened to have a browser pointed at the tekton page.  However the error message cleared itself up while I was considering grabbing a screenshot, as the component continuously polls for updates.  I did this testing with the 1.0 pre-release image, but if there's a more relevant setup to try like maybe running with a local instance separate from the cluster I can try that too.

If our component poll regularly then I think there's not much more we can do to cover transient issues between the backstage backend and the clusters it's configured to proxy requests to other than report problems right away like we do.  We could think about another layer of error reporting where maybe some cases don't need to be immediately reported to the user and the UI just gracefully handles it.

In any case, I think the error reporting as implemented is much better than what's shown in the original screenshots, where there's no mention of an actual error, just no pipelines which is confusing.  A warning notification that there's been a problem querying the cluster is much more helpful.

**Comment by jerolimov** [comment] 2024-01-30 19:54
As discussed, we can and will improve the plugin in the future. However, we can not DNS or network issues in the plugin. We show errors now and improved the rendering a bit.

I'm closing this now and we think we should open a new one when this or a similar error occurs again.

**Closed by jerolimov** 2024-01-30 19:54 UTC
Labels: kind/bug, plugin/tekton, status/triage
