### ISSUE TITLE
Matomo analytics doesn't work

### ISSUE THREAD

**Issue by goququ** [janus-idp/backstage-plugins#1294] opened 2024-02-29 11:11 UTC
### Describe the bug

I have installed the matomo analytics plugin according the docs, but the default events of backstage don't track. So I fixed it by replacing this part of code:

```typescript
// plugins/analytics-module-matomo/src/api/index.ts

captureEvent(event: AnalyticsEvent) {
    const { context, action, subject, value } = event;

    // OLD: this.paq.push([
    window._paq.push([
      'trackEvent',
      context.extension || 'App',
      action,
      subject,
      value,
    ]);
  }
```

### Expected Behavior

I expect api calls to matomo instance while I navigate on backstage.

### What are the steps to reproduce this bug?

1. Setup matomo analytics plugin
2. Check api calls on Network tab, while you are working on backstage.

### Versions of software used and environment
OS:   Darwin 23.3.0 - darwin/arm64
node: v18.19.1
yarn: 1.22.21
cli:  0.25.1 (installed)
backstage:  1.22.1

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.5.13
  @backstage/backend-common                                        0.19.9, 0.20.1, 0.21.2
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.6.12
  @backstage/backend-tasks                                         0.5.17
  @backstage/backend-test-utils                                    0.2.10
  @backstage/catalog-client                                        1.6.0
  @backstage/catalog-model                                         1.4.4
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.3
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.2
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.12.0
  @backstage/core-compat-api                                       0.1.1, 0.2.0
  @backstage/core-components                                       0.13.10, 0.14.0
  @backstage/core-plugin-api                                       1.9.0
  @backstage/dev-utils                                             1.0.26
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0, 0.6.0
  @backstage/integration-aws-node                                  0.1.9
  @backstage/integration-react                                     1.1.24
  @backstage/integration                                           1.9.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.4.7
  @backstage/plugin-badges-backend                                 0.3.6
  @backstage/plugin-badges                                         0.2.53
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.6
  @backstage/plugin-catalog-backend-module-ldap                    0.5.24
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.6
  @backstage/plugin-catalog-backend                                1.16.1
  @backstage/plugin-catalog-common                                 1.0.21
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.7.2
  @backstage/plugin-catalog-react                                  1.10.0
  @backstage/plugin-catalog-unprocessed-entities                   0.1.7
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-entity-feedback-backend                        0.2.6
  @backstage/plugin-entity-feedback-common                         0.1.3
  @backstage/plugin-entity-feedback                                0.2.12
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-backend                             0.5.32
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.23
  @backstage/plugin-permission-react                               0.4.20
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.16
  @backstage/plugin-search-backend-node                            1.2.16
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.6
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-sentry                                         0.5.14
  @backstage/plugin-techdocs-backend                               1.9.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.4
  @backstage/plugin-techdocs-react                                 1.1.16
  @backstage/plugin-techdocs                                       1.10.0
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.4.4, 0.5.1
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

**Comment by akhilmhdh** [comment] 2024-03-13 05:55
Hey @invincibleJai 

Sadly i am not part of the backstage red hat team anymore. As an open-source project yes but lacking a bit of bandwidth at present. 

I think @riginoommen should be able to look into it

**Comment by deshmukhmayur** [comment] 2024-03-15 09:31
Thanks for reporting and identifying the cause @goququ. I can send a quick fix for this shortly.

@invincibleJai Can you assign this issue to me?

**Closed** 2024-03-15 11:11 UTC
Labels: kind/bug, status/triage, jira
