### ISSUE TITLE
🔌 Plugin: Ansible Automation Platform  

### ISSUE THREAD

**Issue by regicsolutions** [janus-idp/backstage-plugins#189] opened 2023-03-22 13:54 UTC
### 🔖 Summary

A plugin to enable an environment as a service type approach using Ansible Automation Platform as the Orchestrator responsible for managing application environments and its state. 

AAP is able to make use of [Event-Driven Ansible ](https://www.ansible.com/blog/introducing-event-driven-ansible) where we can benefit from the new [backstage event-backend plugin system](https://github.com/backstage/backstage/tree/master/plugins/events-backend ) Where if a events-backend-module-ansible existed, similar to the [aws-sqs module](https://github.com/backstage/backstage/tree/master/plugins/events-backend-module-aws-sqs) plugin could introduce the next lean, event-driven infrastructure and dynamic configuration management orchestration engine! 

From a front-end perspective, visualizing the environments at the component and system level would be insightful. 

### ✌️ Context

Sample Implementations with other orchestration tools:
- [Cloudify](https://cloudify.co/blog/the-entire-software-development-process-open-source-and-automated-via-backstage/) 

- [AWS Proton](https://aws.amazon.com/blogs/containers/provisioning-infrastructure-using-the-aws-proton-open-source-backstage-plugin/)

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by serenamarie125** [comment] 2023-04-27 22:49
@cooktheryan presented some introductory work in this area at today's Janus Community call - take a look at the recording: https://www.youtube.com/watch?v=g9h7XdjSn08&t=24s 

Feel free to add input here to include additional requirements, comments, etc.

**Comment by jasperchui** [comment] 2023-07-20 18:32
Close this as duplicate of #481

**Closed by jasperchui** 2023-07-20 18:32 UTC
Labels: duplicate
