### ISSUE TITLE
Keycloak: Importing users without first AND last name properties fails

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#579] opened 2023-07-27 13:16 UTC
**Describe the bug**
If a Keycloak user doesn't have BOTH first and last name, the import to Backstage fails

**To Reproduce**

1. `yarn workspace @janus-idp/backstage-plugin-keycloak-backend start`
2. A browser with `http://localhost:8080/admin/master/console/#/janus-realm` will open
3. Wait for Keycloak Admin console from previous step to start
4. Log in with `admin` username and `admin` password
5. Go to **Users** in the left menu
6. Click **Add User**
7. Fill in **Username** only and click create
8. Observe logs:

```
@janus-idp/backstage-plugin-keycloak-backend:start:plugin: 2023-07-27T12:54:22.194Z catalog info Read 1 Keycloak users and 1 Keycloak groups in 0.1 seconds. Committing... type=plugin class=KeycloakOrgEntityProvider taskId=KeycloakOrgEntityProvider:default:refresh taskInstanceId=82cacfdf-74c3-45f3-83a1-85eec47c43f6
@janus-idp/backstage-plugin-keycloak-backend:start:plugin: 2023-07-27T12:54:22.198Z catalog info Committed 1 Keycloak users and 1 Keycloak groups in 0.0 seconds. type=plugin class=KeycloakOrgEntityProvider taskId=KeycloakOrgEntityProvider:default:refresh taskInstanceId=82cacfdf-74c3-45f3-83a1-85eec47c43f6
@janus-idp/backstage-plugin-keycloak-backend:start:plugin: 2023-07-27T12:54:22.264Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity user:default/test; caused by TypeError: /spec/profile/displayName must NOT have fewer than 1 characters - limit: 1 type=plugin entity=user:default/test location=url:http://localhost:8080/admin/realms/janus-realm/users/b86c34f8-daf3-4075-9fa9-312a702b0a10
```

**Expected behavior**
User is ingested

**Screenshots**

**Additional context**
This is a good starting issue for troubleshooting the Keycloak plugin and learning about this repository. Please do not work on this, unless you are getting started around here. 🙂

**Comment by navinyashende** [comment] 2023-07-30 09:21
I would like to work on this.

**Comment by navinyashende** [comment] 2023-07-30 09:23
As per my analysis, the displayName is populated using combination of firstName and lastName. The check for displayName being non-empty is in backstage code. Can we populate displayName as username if both firstName and lastName are empty?

**Comment by schultzp2020** [comment] 2023-08-11 13:48
@tumido this is a duplicate of https://github.com/janus-idp/backstage-plugins/issues/274

**Comment by navinyashende** [comment] 2023-08-11 14:04
@schultzp2020 I see that you have closed your linked PR for #274. Since you are already working on that, can we close this issue?

**Comment by schultzp2020** [comment] 2023-08-11 14:06
@navinyashende I'm not currently working on it. I can assign you if you'd like. I'll close this issue one you respond.

**Comment by navinyashende** [comment] 2023-08-12 14:04
@schultzp2020 Sounds good to me. Please assign the original issue and close the current one

**Closed** 2023-08-14 14:38 UTC
Labels: kind/bug, good first issue, plugin/keycloak, status/triage
